### ISSUE TITLE
Loader issue

### ISSUE THREAD

**Issue by ritika728** [codervivek5/Formfil.in#101]
Hey, I would like to open this issue under JWOC. 
The loader on the home page is not stopping because of missing JavaScript. I would like to modify the loader and add the essential JavaScript, HTML and CSS required to improve the overall functionality and look of the loader. Thank you!

https://user-images.githubusercontent.com/91181981/220387078-48ba3eee-1ece-4ec0-acea-9b76d3427bd0.mp4

**Comment by VaibhavTalkhande** [comment]
i have fixed that issue in my issue already

**Comment by codervivek5** [comment]
@VaibhavTalkhande show me video ..If you have solve it then after reviewing I'll merge your pr

**Comment by VaibhavTalkhande** [comment]
ok

**Comment by VaibhavTalkhande** [comment]
should i send a video here or in discord

**Comment by VaibhavTalkhande** [comment]
https://user-images.githubusercontent.com/49303222/220535793-ff268f43-bda1-4f1c-8aaa-b637ac7f37d6.mp4

**Comment by VaibhavTalkhande** [comment]
you can assign this to me as i wil send pr

**Comment by ritika728** [comment]
@VaibhavTalkhande but since you are already assigned to one issue, and only one issue is permitted per project, i could resolve this one. Issue was opened by me only though 😅

**Comment by VaibhavTalkhande** [comment]
Ya I know but I already had done with it talk to him about this  before issue on discord
That's why 😅

**Comment by ritika728** [comment]
Oh It's alright then! No problem at all💫

**Comment by codervivek5** [comment]
@ritika728 If you are working in this project then continue....but if you want to assign if to other candidate then drop a comment here.

**Comment by ritika728** [comment]
Yes, I am working on this. Will submit a pull request today itself

**Comment by ritika728** [comment]
@codervivek5 right now the loader appears only on the home page, do you want me to correct it and add it on all the pages or just the home page ?

**Comment by codervivek5** [comment]
@ritika728 
Actually vaibhav had done this task and also he send me for the review...I you agree then he can create his PR :)

**Comment by ritika728** [comment]
Yes yes sure, no issues! ✨

**Comment by VaibhavTalkhande** [comment]
Ok

**Comment by codervivek5** [comment]
ok
