### ISSUE TITLE
Landing page not visible upon opening the website

### ISSUE THREAD

**Issue by AK-shat-JAIN** [codervivek5/Formfil.in#108]
Hello sir @codervivek5 
As the landing page is not visible will shift the landing page content to the index page and it will redirect it to the home page(renamed index page).
then "FORM FILL" animation will be visible

**Comment by codervivek5** [comment]
yes bro...I have create a issue for it...If you can do it then definitely try to drop a comment as possible as soon

**Comment by AK-shat-JAIN** [comment]
Sr that's not fair I am looking to contribute for this

**Comment by codervivek5** [comment]
ok dude! no worry let me check once :)

**Comment by AK-shat-JAIN** [comment]
Thanks a lot sr for understanding the concern  : )
