### ISSUE TITLE
About us page not linked with Index.html

### ISSUE THREAD

**Issue by tmsagarofficial** [codervivek5/Formfil.in#110]
The about us section in the website is not accessible and hence shows the following .
https://codervivek5.github.io/Formfil.in/about-us.html
![image](https://user-images.githubusercontent.com/110724849/221117002-0ec8a1ed-b819-472d-b0e4-122908916ca5.png)

I would love to work on this under jwoc

**Comment by TuhinBanerjee31** [comment]
I want to work on this issue under JWOC

**Comment by codervivek5** [comment]
some one it already working on it....this page already created but due to the bug it is not visible so assigned mentees will solve this.
