### ISSUE TITLE
Improvement of Homepage Responsiveness

### ISSUE THREAD

**Issue by TuhinBanerjee31** [codervivek5/Formfil.in#111]
I want to work on this issue under JWOC

**Comment by codervivek5** [comment]
actually someone is already working in this issue so wait till tomorrow.... I will assign it to if they can do it.

**Comment by TuhinBanerjee31** [comment]
okay

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by codervivek5** [comment]
@TuhinBanerjee31 any update?

**Comment by TuhinBanerjee31** [comment]
Will raise a PR by tonight.

**Comment by codervivek5** [comment]
ok
