### ISSUE TITLE
Index and landing page Bug

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/Formfil.in#112]
If any body want to contribute in this issue then read it very careful

- you have remove or rename  (file name - landing page) to (file name - Index.html)
- there is already present a file with name Index.html, so its totally depend on you that how can you manage it. but try to run both file separatory(I thing landing.html file is bug free so you can use that file, but try once.)
- Here landing page is known as index.html file name so no need to make a separate file with any other name
- file and folder structure will be as I giving you

> pages
 -here you set all the html page except index.html

>styles
-here you set all the CSS file

>scripts
-here you can set all the script files

>Images
-here you can set all the type of image (if you want to convenient then create sub-folder inner this folder according to use case)

**Note** - Do not make any changes in any other file and folder leave as it is.

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by VaibhavTalkhande** [comment]
I would like to work on issues under jwoc

**Comment by codervivek5** [comment]
remember one thing....give me output of you completion as a link (like GitHub page link)

**Comment by AK-shat-JAIN** [comment]
I want to work under this issue @codervivek5 Please assign it to me

**Comment by codervivek5** [comment]
Guys actually this issue is created by @AK-shat-JAIN so firstly I have to assign it to him. If they are not able to do it with given time then I will assign it to you guys.
