### ISSUE TITLE
footer section fix

### ISSUE THREAD

**Issue by VaibhavTalkhande** [codervivek5/Formfil.in#113]
there is inconsistency in footer section of different pages you can see that .i would like to fix it @codervivek5 

![Screenshot (6)](https://user-images.githubusercontent.com/49303222/221244185-e562bfa9-420c-4f55-a87a-dafe0fb53778.png)
![Screenshot (7)](https://user-images.githubusercontent.com/49303222/221244201-a570be7e-e66c-4b19-8308-8d52a3ce2a79.png)
![Screenshot (8)](https://user-images.githubusercontent.com/49303222/221244207-4d9731c9-be5f-47c4-94e5-9a7a26bc1260.png)
![Screenshot (9)](https://user-images.githubusercontent.com/49303222/221244214-74e24f9b-9839-46f3-894c-a67132af69ca.png)

**Comment by codervivek5** [comment]
Transparent footer is not looking good.

**Comment by VaibhavTalkhande** [comment]
ya every page has different style of footer section

**Comment by codervivek5** [comment]
if you come here then you can reduced the height of footer so and make it responsive.
add my mail - codervivek5@gmail.com
add services - PAN services, Passport service, Aadhar service and more according to you

**Comment by codervivek5** [comment]
add footer on every page

**Comment by VaibhavTalkhande** [comment]
yes

**Comment by codervivek5** [comment]
if you have any doubt then feel free to ask me...I accepted your request on discord so you can connect with me

**Comment by codervivek5** [comment]
![image](https://user-images.githubusercontent.com/62784060/221247962-06dd9fbb-6680-4f0d-8d33-6f66a1c7db1e.png)

**Comment by VaibhavTalkhande** [comment]
if you come here then you can reduced the height of footer so and make it responsive.
add my mail - [codervivek5@gmail.com](mailto:codervivek5@gmail.com)
add services - PAN services, Passport service, Aadhar service and more according to you
i can also do it but i will take time to add all of these  can you make difficulty level  to hard

**Comment by codervivek5** [comment]
you can refer this image
change **contact** to **support** and add some links like FAQ, Contact us

**Comment by codervivek5** [comment]
ok I will change the difficulty level

**Comment by codervivek5** [comment]
No need to make it  from scratch....just try to fix bug and change the name as I tell you

**Comment by VaibhavTalkhande** [comment]
Ok

**Comment by VaibhavTalkhande** [comment]
just sent you a pr

**Comment by codervivek5** [comment]
I will give you feedback......kindly try to fix those things

**Comment by VaibhavTalkhande** [comment]
Just send a pr, check it  please

**Comment by VaibhavTalkhande** [comment]
Check my pr

**Comment by codervivek5** [comment]
ok

**Comment by VaibhavTalkhande** [comment]
Please check my pr i have to do changes again and again due to some othe guy merged pr please first check mine pr .I am only working on this issue because of that
