### ISSUE TITLE
Improvement of Contact Us page Responsiveness

### ISSUE THREAD

**Issue by pooranjoyb** [codervivek5/Formfil.in#117]
# Description
### The Contact Us page is not responsive and breaks in mobile versions.

# Related Screenshots : 

![demo](https://user-images.githubusercontent.com/90945182/221340256-ab541814-169f-4a23-a630-682691871eff.png)

## I would like to work on this issue under JWOC 2023. Please assign this issue to me. @codervivek5

**Comment by codervivek5** [comment]
any update?

**Comment by pooranjoyb** [comment]
Yes, almost done. Submitting PR in 30 mins. @codervivek5
