### ISSUE TITLE
Design a UI for user profile with dashboard 

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/Formfil.in#13]
You have design a user profile with their name, mobile number, email, services ,a document section and all possible thinks wish a dashboard functionally.
So that user can handle all things.

**Comment by sagnik3788** [comment]
i want work on this under jwoc

**Comment by codervivek5** [comment]
@sagnik3788 you can only work in one issue at a time. 
wait for the next....

**Comment by PrachiSingh66** [comment]
Hii, I want to work on this issue under JWOC so please assign it to me.
Thank you

**Comment by Saedbhati** [comment]
I want to do this

**Comment by PrachiSingh66** [comment]
Sir please attach JWOC label with this issue. And from where we can see our points.

**Comment by codervivek5** [comment]
By mistake issue can be labelled, you can see your points after 1 phases completed in official site.
Organisation will update your points in official site and give you message to see your points

**Comment by codervivek5** [comment]
Don't worry about that.

**Comment by PrachiSingh66** [comment]
Ok sir thank you

**Comment by codervivek5** [comment]
👍
