### ISSUE TITLE
Make the navbar sticky

### ISSUE THREAD

**Issue by Neha00011** [codervivek5/Formfil.in#130]
I want to make the navbar fix to its position and it will change color while scrooling. that will improve the UI.
Kindly assign this issue to me under JWOC.

**Comment by rko0211** [comment]
Kindly assign this issue to me under JWOC. I want to work on this issue.

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC
