### ISSUE TITLE
Adding some documentation

### ISSUE THREAD

**Issue by Sowham-3098** [codervivek5/Formfil.in#14]
1. adding code_of_conduct.md
2. adding the license.md
3. adding contributor's profile section in the readme.md

**Comment by Sowham-3098** [comment]
PLease assign this to me under JWOC

**Comment by Sowham-3098** [comment]
Please add JWOC tag to this issue

**Comment by codervivek5** [comment]
I Would assign this times to you but you close it all the time ?

**Comment by Sowham-3098** [comment]
Sorry, I closed that issue because that was created before 15th FEB. please add the tag in this issue. I will work on it.

**Comment by codervivek5** [comment]
No worry about that yu can make changes till now

**Comment by Sowham-3098** [comment]
Can you add the jwoc and other tags to this issue?

**Comment by codervivek5** [comment]
just wait

**Comment by codervivek5** [comment]
Now you can start your contribution

**Comment by Sowham-3098** [comment]
Please check your discord DM once!
