### ISSUE TITLE
BUG-There is a bug in the navbar that when we are going through other page then also line is coming under home page. I want to correct it.

### ISSUE THREAD

**Issue by aadrikasingh18** [codervivek5/Formfil.in#15]

**Comment by aadrikasingh18** [comment]
I want to work on this issue under JWOC, please assign it to me.

**Comment by Codey001** [comment]
i want to work on the issue

**Comment by Codey001** [comment]
i want to work on the issue under JWOC

**Comment by codervivek5** [comment]
any update ??

**Comment by codervivek5** [comment]
IF you have done anything just show me via the link, or screen shot. after review I will merged your PR.

In case I miss your Request then Kindly send back to me.

**Comment by codervivek5** [comment]
yeah!

**Comment by ishita-singhal** [comment]
@aadrikasingh18 This issue has been already solved. I guess you have forked the previous code or may not have updated it.

**Comment by codervivek5** [comment]
Can you generate page link with your ID so that I can review it
