### ISSUE TITLE
Create a Cart page for user service

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/Formfil.in#24]
you can create a cart page where users can add the services, whose they want.

**Comment by Neha00011** [comment]
I want to work on this issue under JWOC.

**Comment by harshit21-02** [comment]
I want to work on this issue. please assign

**Comment by Neha00011** [comment]
![Screenshot (67)](https://user-images.githubusercontent.com/112271756/219473813-d3d751dd-2957-42cc-bf28-7c14fbb2e033.png)
@codervivek5 is it ok?Can I make a pr now?
