### ISSUE TITLE
Create a checkout page

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/Formfil.in#25]
Here users can check their service and submit all for the payment process

**Comment by bhavya321321** [comment]
i want to work on this issue under JWOC please assign me

**Comment by harshit21-02** [comment]
I want to work on this issue. please assign

**Comment by bhavya321321** [comment]
ok sir i have to work on it

**Comment by bhavya321321** [comment]
Ok sir i will make check out page

**Comment by sandeeprawat28** [comment]
Please give me this issue, I will make it interactive and user-friendly.

**Comment by codervivek5** [comment]
@bhavya321321 any update?

**Comment by bhavya321321** [comment]
i am working sir

**Comment by bhavya321321** [comment]
sir what change i should made please suggest

**Comment by codervivek5** [comment]
can you share screeshot again then I will suggest you

**Comment by bhavya321321** [comment]
ok

**Comment by bhavya321321** [comment]
![Uploading image1jpeg.jpeg…]()
