### ISSUE TITLE
Create a payment page

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/Formfil.in#26]

**Comment by SasiVardhan247** [comment]
I want to work on this issue under JWOC, can you assign me this @codervivek5

**Comment by bhavya321321** [comment]
I want to work on this issue under JWOC please assign me

**Comment by harshit21-02** [comment]
I want to work on this issue. please assign

**Comment by sandeeprawat28** [comment]
Please give me this issue, I will make it interactive and user-friendly.
