### ISSUE TITLE
Make navigation bar with menu

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/Formfil.in#3]
Create a navigation bar for these related menus. you have to create this navbar at the top of the website. you have also included a website LOGO.

**Comment by codervivek5** [comment]
Make this sticky navigation bar on the top.

**Comment by KrunalGupta02** [comment]
Hi i would like to work on this issue and i have one enhancement by adding the hamburger menu for the mobile devices.

**Comment by Suniti-0020** [comment]
hi @codervivek5 I would like to work on the issue . 
Can you assign it to me.  under JWOC

**Comment by Codey001** [comment]
I want to work on this issue under JWOC

**Comment by SubhajitB05** [comment]
"I want to work on this issue under JWOC"

**Comment by codervivek5** [comment]
@Suniti-0020  there is any update ?

**Comment by Suniti-0020** [comment]
Sir,
 I will update you at 4 pm  . Sorry for your wait ....

Suniti

**Comment by codervivek5** [comment]
Ok

**Comment by Suniti-0020** [comment]
@codervivek5 I have resolved the problem from my side . Please try again
