### ISSUE TITLE
Add a favicon to the website

### ISSUE THREAD

**Issue by Laxmankohar** [codervivek5/Formfil.in#35]
Hey @codervivek5 , I would like to work on this issue under JWOC. Can you please assign it to me?

**Comment by codervivek5** [comment]
Drop a msg in discord for logo so that you can make that as a favicon

**Comment by Laxmankohar** [comment]
Can i use this as  it is already present in the img folder?

![image](https://user-images.githubusercontent.com/73365025/219038325-12eb7e62-c362-4556-836c-f71d379e511b.png)

**Comment by codervivek5** [comment]
Ok you can use it
