### ISSUE TITLE
Re-Design UI of Landing Page 

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/Formfil.in#4]

**Comment by codervivek5** [comment]
You can Refer this design.
https://www.figma.com/file/1ttT5esi2iem3HDRat3oTv/CAFE-APP?t=iQg43K4pAqTd5ZEt-1

**Comment by itsshahinhere** [comment]
please grant permission to access the file
thank you!

**Comment by Dinokojt7** [comment]
Hi which of these pages is landing? you have dashboard, login etc. none is named landing

**Comment by codervivek5** [comment]
Home page is landing page for UI design

**Comment by sagnik3788** [comment]
i want to work on this under JWOC

**Comment by sagnik3788** [comment]
should i create a new UI landing page?

**Comment by codervivek5** [comment]
yeah ! you can try with same design as is it but try to change the color with some color palette.
I would pin a sample in discord or you can drop a msg I will send it again then you can use as reference for you

**Comment by sagnik3788** [comment]
ok sir

**Comment by sagnik3788** [comment]
i completed it but i cant make a pr

**Comment by codervivek5** [comment]
Show Me output if everything will be fine then I will help you to make you PR successful

**Comment by sagnik3788** [comment]
![Uploading Screenshot_20230215_185031.png…]()

**Comment by sagnik3788** [comment]
> Show Me output if everything will be fine then I will help you to make you PR successful

![Screenshot_20230215_185031](https://user-images.githubusercontent.com/116512372/219042464-9925dace-16d1-4ae6-b664-f8117dbb91bb.png)

**Comment by codervivek5** [comment]
You should update home page without cleaning. Design is pretty good but do not remove any thing. Only update this design with old one .

**Comment by sagnik3788** [comment]
i dont remove anything i just change the color

**Comment by sagnik3788** [comment]
old one means that figma landing page?

**Comment by codervivek5** [comment]
I will raised a new issue. You can work on that. 
Actually this is for UI design and another candidate is already working on it. You can comment in new issue with same work ( coding).

**Comment by sagnik3788** [comment]
ok sir

**Comment by Saedbhati** [comment]
I am doing design work on these platform

**Comment by codervivek5** [comment]
Yeah. Just wait

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC
