### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/Formfil.in#5]

**Comment by rsarthak** [comment]
Hey, please assign this to me.

**Comment by codervivek5** [comment]
I will assign it when contribution will be started so kindly wait till 15 Feb.

**Comment by rsarthak** [comment]
Okay

**Comment by codingis4noobs2** [comment]
Hello @codervivek5 , i would like to work on this project 🚀, I want to work on this issue under JWOC.

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by codingis4noobs2** [comment]
@codervivek5 pls tell the dimensions of the logo.

**Comment by codervivek5** [comment]
there are multiple dimensions 
you can refer it via google.
you can make it 500px X 500px


make it for android app also we can use for websites also
