### ISSUE TITLE
Contributors are not visible in readme.md

### ISSUE THREAD

**Issue by shreyanka155** [codervivek5/Formfil.in#52]
I want to work on this issue under jwoc. Please assign me this issue.

**Comment by tmsagarofficial** [comment]
@codervivek5 I would love to work on this issue. under jwoc

**Comment by codervivek5** [comment]
@shreyanka155 any update.

**Comment by shreyanka155** [comment]
> @shreyanka155 any update.

Yess sir I'm working on it, will fix it within today.

**Comment by shreyanka155** [comment]
> @shreyanka155 any update.

Yess sir I'm working on it, will fix it within today.

**Comment by codervivek5** [comment]
Ok

**Comment by codervivek5** [comment]
any update ?
