### ISSUE TITLE
Updating the README

### ISSUE THREAD

**Issue by the-amazing-atharva** [codervivek5/Formfil.in#57]
I would like to work on the README to make it more visually appealing and also add badges for tech stacks.
Some images are broken that can be fixed too.

**Comment by codervivek5** [comment]
Also try to add contributor image with there profile

**Comment by the-amazing-atharva** [comment]
Sure 
Working on it !

**Comment by Code1705** [comment]
I want to contribute in this issue by making a proper informative rules about the contribution process and a compact readme file to look attractive, please assign me under JWOC.

**Comment by codervivek5** [comment]
@the-amazing-atharva any update?

**Comment by the-amazing-atharva** [comment]
> @the-amazing-atharva any update?

I have to add social links right?
Could you send it here and i'll quickly add them
