### ISSUE TITLE
Re- design App logo

### ISSUE THREAD

**Issue by kushaljgec2025** [codervivek5/Formfil.in#61]
I want to do this under JWOC

**Comment by codervivek5** [comment]
Remember one thing after design LOGO send screenshot here or. In discord channel

**Comment by codervivek5** [comment]
With your issue number and name

**Comment by kushaljgec2025** [comment]
Ok , can I make more than one design

**Comment by codervivek5** [comment]
Yea try to make more then one so then i can differentiate and best of one

**Comment by tmsagarofficial** [comment]
@codervivek5 assign this to me under jwoc if no one is currently working on the same

**Comment by kushaljgec2025** [comment]
@tmsagarofficial I am currently working on that.

**Comment by codervivek5** [comment]
@kushaljgec2025 any update.

**Comment by kushaljgec2025** [comment]
Yes @codervivek5  I have done 3 logos 
![Design 1](https://user-images.githubusercontent.com/108950724/219847444-202abfc3-a700-4a7b-81a3-380148c1176f.png)
![design 2](https://user-images.githubusercontent.com/108950724/219847445-c6ffeb52-ba2b-4e6a-915f-3b5d45697aa6.png)
![design 3](https://user-images.githubusercontent.com/108950724/219847447-7f901008-e028-4f28-9a4e-760dc0299871.png)
. And also making very few.

**Comment by codervivek5** [comment]
Not looking good ....try to use any AI tool to generate logo

**Comment by codervivek5** [comment]
@tmsagarofficial try to make logo with similar to the meaning ( Formfil - Digital cyber cafe in hand )

**Comment by kushaljgec2025** [comment]
Is it required that logo contain the Form fill name? Or only FF

**Comment by codervivek5** [comment]
Some reated to this ....if you can make it better then use only FF

**Comment by kushaljgec2025** [comment]
Ok I can also make icon for that also related to this.

**Comment by codervivek5** [comment]
Yes sure

**Comment by tmsagarofficial** [comment]
ok on it @codervivek5

**Comment by codervivek5** [comment]
No issues you can work but design a perfect...

**Comment by kushaljgec2025** [comment]
![Artboard 1](https://user-images.githubusercontent.com/108950724/219869794-92b16f97-fb81-418b-9907-f095585dc4a7.png)
![FromFil in](https://user-images.githubusercontent.com/108950724/219869796-45eaf675-bcfd-455e-a6fa-9b2542230de1.png)

**Comment by kushaljgec2025** [comment]
is it good

**Comment by codervivek5** [comment]
can you make some more ?
with different desing

**Comment by kushaljgec2025** [comment]
Yeh .I am doing that .please clear me what r u want like it's contains the nam or it's contains the theme or it contains sometimes about form fill. Please clear me . It will help me to design perfect

**Comment by codervivek5** [comment]
Actually, your design was good but I want a design that can fit everywhere like the android apps, and social media (Instagram, FB, Whatsapp). 
I also can make a animation Intro for that.

**Comment by kushaljgec2025** [comment]
![Screenshot 2023-02-18 232217](https://user-images.githubusercontent.com/108950724/219880864-4c23649d-618b-48fa-a8f5-b9f42e4502d8.png)
R u like this typeof simplistic design

**Comment by codervivek5** [comment]
can you change color
and reduces FF size

**Comment by kushaljgec2025** [comment]
![Uploading Screenshot 2023-02-18 232453.png…]()

**Comment by kushaljgec2025** [comment]
![Screenshot 2023-02-18 232453](https://user-images.githubusercontent.com/108950724/219881008-aef31bb7-122e-461a-ab27-543726dd803b.png)

**Comment by kushaljgec2025** [comment]
![Screenshot 2023-02-18 232453](https://user-images.githubusercontent.com/108950724/219881073-9bcddc07-9828-48a5-8175-7f55b59b55e6.png)

**Comment by codervivek5** [comment]
Kindly discuss with me in discord in separate window.
so that we can talk easly

**Comment by kushaljgec2025** [comment]
Ok u r talking about thread right?

**Comment by codervivek5** [comment]
I am talking about personal chat dude!

**Comment by kushaljgec2025** [comment]
ok
