### ISSUE TITLE
Fix the File and Folder structure 

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/Formfil.in#63]
In this issue, you have to fix the folder and image structure and link all the pages to the proper place.
like the login page,register page.

Remember one thing:-
You do not have to create anything only you have fixed the structure of the project

**Comment by SarveshGholap** [comment]
I want to work on this issue under jwoc

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue please assign this issue to me under jwoc.

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC @codervivek5

**Comment by ishita-singhal** [comment]
Sir,I want to work on this issue.

**Comment by codervivek5** [comment]
@SarveshGholap before starting your work, Kindly discuss with me in discord.

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by manya0210** [comment]
Hello sir... I want to work on this issue under jwoc

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC @codervivek5

**Comment by codervivek5** [comment]
@SarveshGholap any update ???

**Comment by SarveshGholap** [comment]
Yes i am working

**Comment by codervivek5** [comment]
ok

**Comment by codervivek5** [comment]
Bro create a page link and send me for review

**Comment by codervivek5** [comment]
if you dont know github page link. just tell me I will help you to create that

**Comment by SarveshGholap** [comment]
Yes I don't know GitHub page link

**Comment by codervivek5** [comment]
drop a message in discord...I will helped you on there

**Comment by codervivek5** [comment]
any update ?

**Comment by tmsagarofficial** [comment]
assign it to under jwoc if possible
