### ISSUE TITLE
Create Sign Up & login Page and link them

### ISSUE THREAD

**Issue by Ritu-2001** [codervivek5/Formfil.in#7]

**Comment by priyanka1551** [comment]
@codervivek5 I want to work on this issue under JWOC. Can you please assign this issue to me.

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by Atul-8115** [comment]
Hello I want to work on this issue

**Comment by bhavya321321** [comment]
i want to contribute on this issue under JWOC

**Comment by Codey001** [comment]
I want to work on this issue under JWOC

**Comment by SubhajitB05** [comment]
"I want to work on this issue under JWOC"

**Comment by bhavya321321** [comment]
I want to work on this issue under JWoc

**Comment by Nehagaddam2909** [comment]
I want to work on this issue under jwoc

**Comment by Ritu-2001** [comment]
i want to create login page please assign me under JWOC

**Comment by Ritu-2001** [comment]
till login page is not added i found that issue very first time why you does not assign me

**Comment by priyanka1551** [comment]
@codervivek5 merge my pr named "created sign up and login page and linked them"
![loginpage](https://user-images.githubusercontent.com/105537443/219406637-92b3a8b6-d135-43b6-954d-d70973385193.png)
![signuppage](https://user-images.githubusercontent.com/105537443/219406697-12cd40bc-0757-4f81-80b2-b553c03c34a5.png)

**Comment by codervivek5** [comment]
can you update it **login with twitter** to **login with google**

**Comment by priyanka1551** [comment]
> can you update it **login with twitter** to **login with google**

Yeahh sure

**Comment by vatan-prakash** [comment]
I want to work on this issue under jwoc

**Comment by priyanka1551** [comment]
> I want to work on this issue under jwoc

This issue is being already completed and merged @codervivek5 .Please close this issue.
