### ISSUE TITLE
Design a Mobile App UI 

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/Formfil.in#8]
In this issue you have to design a android app UI design will all required pages like login page, sign Up page, Home page, payment age and all

**Comment by Sowham-3098** [comment]
@codervivek5 please assign this to me under JWOC

**Comment by kushaljgec2025** [comment]
I wanted to do this under JWOC

**Comment by Sowham-3098** [comment]
@codervivek5 you can assign this to @kushaljgec2025

**Comment by itsshahinhere** [comment]
is this issue is to just design the mobile app using figma?
like only design and no coding, right ?
if yes, i wanted to do this under JWOC

**Comment by codervivek5** [comment]
Yes only mobile APP UI

**Comment by itsshahinhere** [comment]
Can i have the details of all the pages thats needed ?
- login / signup
- home page
- payment page

and what else is needed ?

**Comment by kushaljgec2025** [comment]
@codervivek5 Sir I have mentioned I want to do this before @itsshahinhere. So Please assign me.

**Comment by itsshahinhere** [comment]
@codervivek5 should i continue ?

**Comment by codervivek5** [comment]
@kushaljgec2025 you can make a logo for App ...i pinned a image in discord if you can make a awesome logo for this project then i will assign you a seperate issue for Design logo for app

**Comment by codervivek5** [comment]
@itsshahinhere drop a message in discord I wil tell you all required things

**Comment by kushaljgec2025** [comment]
> 

Yes I can make a logo  also can i start work on that.

**Comment by codervivek5** [comment]
Yea sure ...drop a comment for logo issue I will assigned you

**Comment by itsshahinhere** [comment]
> @itsshahinhere drop a message in discord I wil tell you all required things

sure sir
