### ISSUE TITLE
Scroll button - bottom to top

### ISSUE THREAD

**Issue by ritika728** [codervivek5/Formfil.in#80]
Hey, I would like to open this issue under JWOC. I'll add a scroll button to move from bottom of a page to the top. I will implement this in each and every page.

**Comment by deepbeatz** [comment]
I want to work on this under JWOC

**Comment by ritika728** [comment]
@codervivek5 hey, can this issue be classified in the medium or hard category ? Since it would involve JavaScript and HTML, CSS as well and would be implemented on every page which would be quite time worthy

**Comment by codervivek5** [comment]
No need for all pages because and backend developer add it for all  dynamically

**Comment by codervivek5** [comment]
You can add it only in home page ... because it will be more scrollable
