### ISSUE TITLE
Add some documentation

### ISSUE THREAD

**Issue by Sowham-3098** [codervivek5/Formfil.in#9]
1. adding code_of_conduct.md
2. adding the license.md
3. adding contributor's profile section in the readme.md

**Comment by Sowham-3098** [comment]
Assign this task to me

**Comment by Sowham-3098** [comment]
Assign this task to me

**Comment by tmsagarofficial** [comment]
Hello @Sowham-3098  i would like to work on this project 🚀, I want to work on this issue under JWOC.
