### ISSUE TITLE
Updating login system in Django project and fix URLS of the project 

### ISSUE THREAD

**Issue by harshit21-02** [codervivek5/Formfil.in#91]
Updating settings page as per requirements and adding required files veiws.py and their urls in urls.py. This will help in making the whole structure of web application.

**Comment by harshit21-02** [comment]
Please share what kind of login system you are expecting and I need to add html files in templates folder for adding urls

**Comment by codervivek5** [comment]
@harshit21-02 there is two type of login admin and user login also
I will add admin login then you will add user login with login page integration.

**Comment by codervivek5** [comment]
@harshit21-02 now you can work on it. I have added admin use name and password and templates and static file. now you can work on it.

I you want to ask anything feel free to ask me

**Comment by harshit21-02** [comment]
Do I also have to enable user login by sending otp on phonenumber or using google account, that requires creating tables. O rjust need to fix and add urls of all pages

**Comment by harshit21-02** [comment]
I have added all missing templates css and js in static and corrected srcs and css links according to django project, rest hrefs will be updated as per views that we will create further, so should I create PR. Login part need models.py to be updates, I think that must be done in a different issue.

**Comment by codervivek5** [comment]
it will be helpful to you to gain more points so my suggestion you can work one by one issue raised by me for back-end

**Comment by codervivek5** [comment]
here you will fix all the url pattern with models

**Comment by harshit21-02** [comment]
okay

**Comment by harshit21-02** [comment]
As you mentioned, I have checked and updated all the files with their resected path and fixed all the URL patterns.

**Comment by codervivek5** [comment]
ok

**Comment by harshit21-02** [comment]
Please merge the pr

**Comment by codervivek5** [comment]
I approved your PR but kindly show me the output then I will merged your PR

**Comment by harshit21-02** [comment]
https://user-images.githubusercontent.com/81517470/221664011-90abcc17-328c-4d53-81d1-3c3b394260aa.mp4

**Comment by harshit21-02** [comment]
https://user-images.githubusercontent.com/81517470/221664536-aa963a95-d2a4-4288-bf17-43f9dbf985b6.mov

**Comment by codervivek5** [comment]
any update ????

**Comment by harshit21-02** [comment]
I had sent you an output video on discord already

**Comment by codervivek5** [comment]
I think I have merged your PR
