### ISSUE TITLE
Content is not there on the home page.

### ISSUE THREAD

**Issue by priyanka1551** [codervivek5/Formfil.in#95]
I want to add content to the home page below digital cyber cafe in reference to the website @codervivek5 
![Screenshot (135)](https://user-images.githubusercontent.com/105537443/220191141-89fe6cbf-c591-40b5-8061-dd014910e04a.png)

**Comment by priyanka1551** [comment]
@codervivek5 Just an update, I am currently working on it and will make the pr by today

**Comment by priyanka1551** [comment]
@codervivek5 please check whether its looking good or not ,then only I will make pr
![Screenshot (144)](https://user-images.githubusercontent.com/105537443/220684234-e97b4e8e-488e-4ea8-94b7-b0e2472d9a72.png)

**Comment by codervivek5** [comment]
can you change this SVG image better then this?

**Comment by priyanka1551** [comment]
> can you change this SVG image better then this?

From which website I can get SVG image?

**Comment by codervivek5** [comment]
https://undraw.co/illustrations

You can refer this site

**Comment by priyanka1551** [comment]
> https://undraw.co/illustrations
> 
> You can refer this site
@codervivek5 please check whether this svg image is looking good or not, then only I will make the final pr
![Screenshot (151)](https://user-images.githubusercontent.com/105537443/221290842-8296a8e7-591a-42a0-84a7-841d26124900.png)

**Comment by codervivek5** [comment]
but try to use is background transparent and copywrite free

**Comment by priyanka1551** [comment]
> but try to use is background transparent and copywrite free

okay sir

**Comment by priyanka1551** [comment]
> but try to use is background transparent and copywrite free

sir, this illustration can't be downloaded for free. on the website you provided, I can't find good illustrations

**Comment by codervivek5** [comment]
okkk I will give you another website for it....just wait

**Comment by codervivek5** [comment]
https://freesvgillustration.com/

Check this one

**Comment by codervivek5** [comment]
https://icons8.com/illustrations/illustration/

**Comment by priyanka1551** [comment]
Sir, I think that the current svg image is better than the one that is present on the images you provided

**Comment by codervivek5** [comment]
I am giving you a image then you will add that ....ok

**Comment by codervivek5** [comment]
https://freesvgillustration.com/product/friends-reference/

**Comment by codervivek5** [comment]
https://icons8.com/illustrations/illustration/pablita-928

**Comment by priyanka1551** [comment]
@codervivek5 How is it looking now? If any change needed, please tell me
![Screenshot (160)](https://user-images.githubusercontent.com/105537443/221430033-9b72b4ed-b59c-4fde-89b5-1566c92378d9.png)

**Comment by codervivek5** [comment]
not looking good

**Comment by codervivek5** [comment]
do not add any svg .......use as default which was already present on it

**Comment by codervivek5** [comment]
for contact issue.............other candidate is already working on it so I think I
 should close this issue........if you see any bug other wise I will close it

**Comment by Code1705** [comment]
Want to add a proper content , please assign me under JWOC.

**Comment by priyanka1551** [comment]
> do not add any svg .......use as default which was already present on it

Okay I will make pr by evening

**Comment by priyanka1551** [comment]
> Want to add a proper content , please assign me under JWOC.

I am working on it
