### ISSUE TITLE
Interlink All the page of the project to each other

### ISSUE THREAD

**Issue by codervivek5** [codervivek5/Formfil.in#97]
After the completed this task, You have to generate a github.io link so that I can review your project.

**Comment by VaibhavTalkhande** [comment]
can i work on it

**Comment by AK-shat-JAIN** [comment]
@codervivek5 I want to work under this issue

**Comment by AK-shat-JAIN** [comment]
@codervivek5 I want to work under this issue

**Comment by codervivek5** [comment]
@VaibhavTalkhande any update?

**Comment by VaibhavTalkhande** [comment]
Will complete it by today

**Comment by codervivek5** [comment]
Do it as soon as possible

**Comment by VaibhavTalkhande** [comment]
you can unassigned this  issue to me as i want to be assigned to loader issue #101 which i have fixed already

**Comment by VaibhavTalkhande** [comment]
https://vaibhavtalkhande.github.io/formfill.github.io/
this is the link
which fixes #97 #103 

https://user-images.githubusercontent.com/49303222/220664886-495a8211-394f-4263-9944-8793bc3c3df6.mp4

**Comment by codervivek5** [comment]
https://vaibhavtalkhande.github.io/formfill.github.io/
You work is grate vaibhav......just give me 1 day for review other candidate....if she is not giving me proper reply then I will merge your PR...
Kindly drop a msg on discord in separate window with this link
I will wait till tomorrow for the reply of ther candidate then i Will assign to you

**Comment by VaibhavTalkhande** [comment]
Thanks 😊

**Comment by codervivek5** [comment]
Thanks for Contribution :)
